initial commit - K8s custom resource type
concourse/resource-types pull request #19
Opened 2020-01-09 01:14 UTC by srinivasa-vasu

Signed-off-by: Srinivasa Vasu <srinivasan.surprise@gmail.com>

2020-01-10 20:37 UTC, YoussB requested changes

2020-01-10 20:37 UTC, YoussB commented on srinivasa-vasu-concourse-k8s.yml
> +name: git
should this be `concourse-k8s`?

2020-01-18 05:01 UTC, srinivasa-vasu commented on srinivasa-vasu-concourse-k8s.yml
> +name: git
done

2020-01-20 15:38 UTC, YoussB commented
seems like there is something wrong with the commits. 2 of them are not signed. If you want I can squash and merge them. Also, the name doesn't seem to be changed.

2020-01-20 16:55 UTC, srinivasa-vasu commented
Pls check now

2020-01-21 16:13 UTC, YoussB commented
My Bad, I added the comment under the `name: git` but on another look, it looked like it is on the name of the file. Now as per the Readme, the name of the file should be `[OWNER_NAME]-[RESOURCE_TYPE_NAME].yml` that should be `srinivasa-vasu-k8s` and the name inside the yaml should look the same as the resource type name when used in a pipeline, thus `k8s`

Unless you disagree, I will update both of them and merge the PR. 
Please reopen if you want to change anything

2020-01-21 16:15 UTC, merged