add artifacthub-resource
concourse/resource-types pull request #59
Opened 2021-01-03 09:18 UTC by PG2000

Signed-off-by: Patrick Geschinski <PG2000@users.noreply.github.com>

2021-01-07 17:04 UTC, muntac commented
@PG2000 Thanks!

2021-01-07 17:06 UTC, muntac requested changes

2021-01-07 17:06 UTC, muntac commented on pg2000-artifacthub-resource.yml
> +  Tracks and get new versions of Helm Charts which are registered at https://artifacthub.io/
@PG2000 small typo:
```suggestion
  Tracks and gets new versions of Helm Charts which are registered at https://artifacthub.io/
```

2021-01-07 17:12 UTC, PG2000 commented
@muntac done.

2021-01-07 18:54 UTC, muntac approved these changes

2021-01-07 18:54 UTC, merged

2021-06-23 13:55 UTC, xtremerui commented
@PG2000 this URL https://github.com/PG2000/artifacthub-resource seems broken as the repo is gone. Could we remove this resource type or you have some other plan? Thx.

2021-06-23 14:08 UTC, PG2000 commented
@xtremerui Hey, i moved the repo to another org and wait for approval until i can make it public again.
So i think it will be available again by the end of the week.
If you like i can open a new pr then.

What do you think?

2021-06-24 13:59 UTC, xtremerui commented
@PG2000 good to know. We will remove it now to fix our CI and add it back later with updated url in your new PR.